<?php

namespace AppBundle\Repository;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        return $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param String $search
     * @return array
     */
    public function lookFor(String $search)//available only PHP 7, in earlier remove type String
    {
        return $this->createQueryBuilder('u')
            ->select('u')
            ->orWhere('u.name LIKE :search')
            ->setParameter(':search','%'.$search.'%')
            ->getQuery()
            ->getResult();
    }
}
